import Head from "next/head";
import { Shelf } from "../components/Shelf/Shelf";
import { SectionHeader } from "../components/SectionHeader/SectionHeader";
import { MediaHero } from "../components/MediaHero/MediaHero";
import { Featurebox } from "../components/Featurebox/Featurebox";
import { useRouter } from "next/router";

import { api } from "~/utils/api";
import { Review } from "~/components/Review/Review";
import { useSession } from "next-auth/react";

export default function Home() {
  const { data: sessionData } = useSession();
  const { data: nowPlaying } = api?.example.nowPlaying.useQuery(undefined);
  const { data: trending } = api?.example.trending.useQuery(undefined);
  const router = useRouter();
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full items-center bg-[#14181c]">
        {!sessionData?.user && (
          <MediaHero url={nowPlaying?.[0]?.backdrop ?? ""}>
            <div className="flex flex-col gap-y-4 ">
              <p className="text-center font-[Lora] text-3xl font-semibold text-white">
                Seamlessly track your show and movie progress.
                <br />
                Stay updated, never miss a beat.
                <br />
                Elevate your entertainment experience.
              </p>
              {/* <Button
                label="Create An Account"
                className={"self-center"}
                size={BUTTON_SIZES.md}
                variant={"primary"}
              /> */}
            </div>
          </MediaHero>
        )}
        <div className="mx-auto  flex h-full w-full max-w-4xl flex-col items-center gap-4 px-20 pt-20">
          {/* Now Playing */}
          <div className="mb-1 w-full">
            <SectionHeader label={"NOW PLAYING"} />
          </div>
          {nowPlaying && (
            <Shelf
              items={nowPlaying
                ?.map((item) => ({
                  url: item?.poster ?? "",
                  onClick: () =>
                    router.push(
                      `/${item?.type === "tv" ? "show" : "film"}/${
                        item?.tmdbId
                      }`
                    ),
                }))
                .slice(0, 5)}
            />
          )}

          {/* Trending TV */}
          <div className="mb-1 w-full">
            <SectionHeader label={"TRENDING TV"} />
          </div>
          {trending && (
            <Shelf
              items={trending
                ?.map((item) => ({
                  url: item?.poster ?? "",
                  onClick: () =>
                    router.push(
                      `/${item?.type === "show" ? "show" : "film"}/${
                        item?.tmdbId
                      }`
                    ),
                }))
                .slice(0, 5)}
            />
          )}
          {!sessionData?.user && <Featurebox />}
          {/* CONTENT */}
          {/* <div className="w-full">
            <div className="">
              <SectionHeader label="POPULAR REVIEWS" />
            <Review />
            <Review />
            <Review />
            </div>
          </div> */}
        </div>
      </main>
    </>
  );
}
